kind: PersistentVolume
apiVersion: v1
metadata:
  name: vpro-db-data
  labels:
    type: amazonEBS
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
